### ISSUE TITLE
Manifest schema version is not supported by quay.io

### ISSUE THREAD

**Issue by leaf-ai-dockerhub** [uber/makisu#189]
When pushing images to quay.io an error is raised concerning the manifest schema version, and the push fails.  The makisu version used was 0.1.9

Will, or should the quay.io registry be supported ?

```
{"level":"error","ts":1551317958.434947,"msg":"failed to push image: failed to push image: push manifest: PUT https://quay.io/v2/leaf_ai_dockerhub/studio-go-runner/manifests/0.9.12-feature-142-makisu-experiment-1gscYp 415: {\"errors\":[{\"code\":\"MANIFEST_INVALID\",\"detail\":{\"message\":\"manifest schema version not supported\"},\"message\":\"manifest invalid\"}]}\n"}         
```

**Comment by copland** [comment]
I'm also running into this issue and did some digging. Based on this [comment]( https://github.com/moby/buildkit/issues/409#issuecomment-394757219) it looks like Quay plans to implement support for Manifest v2-2. They haven't had a [release](https://coreos.com/quay-enterprise/releases/) since July 2018 but my guess is it will be available in the next release since quite a few people are asking for it.

Secondly,  #81 is about adding OCI support to makisu which I think would resolve the issue too.

**Comment by yiranwang52** [comment]
@copland thanks for the digging.
I don't think Makisu should support manifest v1, but we can add OCI support.

**Comment by yiranwang52** [comment]
As commented above, the right solution is for quay.io to support v2 manifest.
